/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as markdownRouteRouteImport } from './routes/(markdown)/route'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShareRouteImport } from './routes/share'
import { Route as markdownHelpRouteImport } from './routes/(markdown)/help'
import { Route as markdownPrivacyRouteImport } from './routes/(markdown)/privacy'
import { Route as markdownTermsRouteImport } from './routes/(markdown)/terms'
import { Route as PlanSettingsRouteImport } from './routes/plan_.settings'
import { Route as ShareImageDotpngRouteImport } from './routes/share_.image[.]png'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const markdownRouteRoute = markdownRouteRouteImport.update({
  id: '/(markdown)',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const markdownHelpRoute = markdownHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => markdownRouteRoute,
} as any)
const markdownPrivacyRoute = markdownPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => markdownRouteRoute,
} as any)
const markdownTermsRoute = markdownTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => markdownRouteRoute,
} as any)
const PlanSettingsRoute = PlanSettingsRouteImport.update({
  id: '/plan_/settings',
  path: '/plan/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareImageDotpngRoute = ShareImageDotpngRouteImport.update({
  id: '/share_/image.png',
  path: '/share/image.png',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inquiry': typeof InquiryRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/help': typeof markdownHelpRoute
  '/privacy': typeof markdownPrivacyRoute
  '/terms': typeof markdownTermsRoute
  '/plan/settings': typeof PlanSettingsRoute
  '/share/image.png': typeof ShareImageDotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inquiry': typeof InquiryRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/help': typeof markdownHelpRoute
  '/privacy': typeof markdownPrivacyRoute
  '/terms': typeof markdownTermsRoute
  '/plan/settings': typeof PlanSettingsRoute
  '/share/image.png': typeof ShareImageDotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(markdown)': typeof markdownRouteRouteWithChildren
  '/inquiry': typeof InquiryRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/(markdown)/help': typeof markdownHelpRoute
  '/(markdown)/privacy': typeof markdownPrivacyRoute
  '/(markdown)/terms': typeof markdownTermsRoute
  '/plan_/settings': typeof PlanSettingsRoute
  '/share_/image.png': typeof ShareImageDotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inquiry'
    | '/plan'
    | '/profile'
    | '/share'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/plan/settings'
    | '/share/image.png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inquiry'
    | '/plan'
    | '/profile'
    | '/share'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/plan/settings'
    | '/share/image.png'
  id:
    | '__root__'
    | '/'
    | '/(markdown)'
    | '/inquiry'
    | '/plan'
    | '/profile'
    | '/share'
    | '/(markdown)/help'
    | '/(markdown)/privacy'
    | '/(markdown)/terms'
    | '/plan_/settings'
    | '/share_/image.png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  markdownRouteRoute: typeof markdownRouteRouteWithChildren
  InquiryRoute: typeof InquiryRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  ShareRoute: typeof ShareRoute
  PlanSettingsRoute: typeof PlanSettingsRoute
  ShareImageDotpngRoute: typeof ShareImageDotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(markdown)': {
      id: '/(markdown)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof markdownRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(markdown)/help': {
      id: '/(markdown)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof markdownHelpRouteImport
      parentRoute: typeof markdownRouteRoute
    }
    '/(markdown)/privacy': {
      id: '/(markdown)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof markdownPrivacyRouteImport
      parentRoute: typeof markdownRouteRoute
    }
    '/(markdown)/terms': {
      id: '/(markdown)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof markdownTermsRouteImport
      parentRoute: typeof markdownRouteRoute
    }
    '/plan_/settings': {
      id: '/plan_/settings'
      path: '/plan/settings'
      fullPath: '/plan/settings'
      preLoaderRoute: typeof PlanSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share_/image.png': {
      id: '/share_/image.png'
      path: '/share/image.png'
      fullPath: '/share/image.png'
      preLoaderRoute: typeof ShareImageDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface markdownRouteRouteChildren {
  markdownHelpRoute: typeof markdownHelpRoute
  markdownPrivacyRoute: typeof markdownPrivacyRoute
  markdownTermsRoute: typeof markdownTermsRoute
}

const markdownRouteRouteChildren: markdownRouteRouteChildren = {
  markdownHelpRoute: markdownHelpRoute,
  markdownPrivacyRoute: markdownPrivacyRoute,
  markdownTermsRoute: markdownTermsRoute,
}

const markdownRouteRouteWithChildren = markdownRouteRoute._addFileChildren(
  markdownRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  markdownRouteRoute: markdownRouteRouteWithChildren,
  InquiryRoute: InquiryRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  ShareRoute: ShareRoute,
  PlanSettingsRoute: PlanSettingsRoute,
  ShareImageDotpngRoute: ShareImageDotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
