/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as planPlanRouteImport } from './routes/(plan)/plan'
import { Route as planProfileRouteImport } from './routes/(plan)/profile'
import { Route as siteIndexRouteImport } from './routes/(site)/index'
import { Route as sitemarkdownRouteRouteImport } from './routes/(site)/(markdown)/route'
import { Route as siteInquiryRouteImport } from './routes/(site)/inquiry'
import { Route as ShareImageDotpngRouteImport } from './routes/share_.image[.]png'
import { Route as planPlanSettingsRouteImport } from './routes/(plan)/plan_.settings'
import { Route as sitemarkdownHelpRouteImport } from './routes/(site)/(markdown)/help'
import { Route as sitemarkdownPrivacyRouteImport } from './routes/(site)/(markdown)/privacy'
import { Route as sitemarkdownTermsRouteImport } from './routes/(site)/(markdown)/terms'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const planPlanRoute = planPlanRouteImport.update({
  id: '/(plan)/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const planProfileRoute = planProfileRouteImport.update({
  id: '/(plan)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const siteIndexRoute = siteIndexRouteImport.update({
  id: '/(site)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const sitemarkdownRouteRoute = sitemarkdownRouteRouteImport.update({
  id: '/(site)/(markdown)',
  getParentRoute: () => rootRouteImport,
} as any)
const siteInquiryRoute = siteInquiryRouteImport.update({
  id: '/(site)/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareImageDotpngRoute = ShareImageDotpngRouteImport.update({
  id: '/share_/image.png',
  path: '/share/image.png',
  getParentRoute: () => rootRouteImport,
} as any)
const planPlanSettingsRoute = planPlanSettingsRouteImport.update({
  id: '/(plan)/plan_/settings',
  path: '/plan/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const sitemarkdownHelpRoute = sitemarkdownHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => sitemarkdownRouteRoute,
} as any)
const sitemarkdownPrivacyRoute = sitemarkdownPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => sitemarkdownRouteRoute,
} as any)
const sitemarkdownTermsRoute = sitemarkdownTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => sitemarkdownRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/share': typeof ShareRoute
  '/plan': typeof planPlanRoute
  '/profile': typeof planProfileRoute
  '/inquiry': typeof siteInquiryRoute
  '/share/image.png': typeof ShareImageDotpngRoute
  '/': typeof siteIndexRoute
  '/plan/settings': typeof planPlanSettingsRoute
  '/help': typeof sitemarkdownHelpRoute
  '/privacy': typeof sitemarkdownPrivacyRoute
  '/terms': typeof sitemarkdownTermsRoute
}
export interface FileRoutesByTo {
  '/share': typeof ShareRoute
  '/plan': typeof planPlanRoute
  '/profile': typeof planProfileRoute
  '/inquiry': typeof siteInquiryRoute
  '/share/image.png': typeof ShareImageDotpngRoute
  '/': typeof siteIndexRoute
  '/plan/settings': typeof planPlanSettingsRoute
  '/help': typeof sitemarkdownHelpRoute
  '/privacy': typeof sitemarkdownPrivacyRoute
  '/terms': typeof sitemarkdownTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/share': typeof ShareRoute
  '/(site)/(markdown)': typeof sitemarkdownRouteRouteWithChildren
  '/(plan)/plan': typeof planPlanRoute
  '/(plan)/profile': typeof planProfileRoute
  '/(site)/inquiry': typeof siteInquiryRoute
  '/share_/image.png': typeof ShareImageDotpngRoute
  '/(site)/': typeof siteIndexRoute
  '/(plan)/plan_/settings': typeof planPlanSettingsRoute
  '/(site)/(markdown)/help': typeof sitemarkdownHelpRoute
  '/(site)/(markdown)/privacy': typeof sitemarkdownPrivacyRoute
  '/(site)/(markdown)/terms': typeof sitemarkdownTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/share'
    | '/plan'
    | '/profile'
    | '/inquiry'
    | '/share/image.png'
    | '/'
    | '/plan/settings'
    | '/help'
    | '/privacy'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/share'
    | '/plan'
    | '/profile'
    | '/inquiry'
    | '/share/image.png'
    | '/'
    | '/plan/settings'
    | '/help'
    | '/privacy'
    | '/terms'
  id:
    | '__root__'
    | '/share'
    | '/(site)/(markdown)'
    | '/(plan)/plan'
    | '/(plan)/profile'
    | '/(site)/inquiry'
    | '/share_/image.png'
    | '/(site)/'
    | '/(plan)/plan_/settings'
    | '/(site)/(markdown)/help'
    | '/(site)/(markdown)/privacy'
    | '/(site)/(markdown)/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShareRoute: typeof ShareRoute
  sitemarkdownRouteRoute: typeof sitemarkdownRouteRouteWithChildren
  planPlanRoute: typeof planPlanRoute
  planProfileRoute: typeof planProfileRoute
  siteInquiryRoute: typeof siteInquiryRoute
  ShareImageDotpngRoute: typeof ShareImageDotpngRoute
  siteIndexRoute: typeof siteIndexRoute
  planPlanSettingsRoute: typeof planPlanSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(plan)/plan': {
      id: '/(plan)/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof planPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(plan)/profile': {
      id: '/(plan)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof planProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/': {
      id: '/(site)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof siteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/(markdown)': {
      id: '/(site)/(markdown)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof sitemarkdownRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/inquiry': {
      id: '/(site)/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof siteInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share_/image.png': {
      id: '/share_/image.png'
      path: '/share/image.png'
      fullPath: '/share/image.png'
      preLoaderRoute: typeof ShareImageDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(plan)/plan_/settings': {
      id: '/(plan)/plan_/settings'
      path: '/plan/settings'
      fullPath: '/plan/settings'
      preLoaderRoute: typeof planPlanSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/(markdown)/help': {
      id: '/(site)/(markdown)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof sitemarkdownHelpRouteImport
      parentRoute: typeof sitemarkdownRouteRoute
    }
    '/(site)/(markdown)/privacy': {
      id: '/(site)/(markdown)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof sitemarkdownPrivacyRouteImport
      parentRoute: typeof sitemarkdownRouteRoute
    }
    '/(site)/(markdown)/terms': {
      id: '/(site)/(markdown)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof sitemarkdownTermsRouteImport
      parentRoute: typeof sitemarkdownRouteRoute
    }
  }
}

interface sitemarkdownRouteRouteChildren {
  sitemarkdownHelpRoute: typeof sitemarkdownHelpRoute
  sitemarkdownPrivacyRoute: typeof sitemarkdownPrivacyRoute
  sitemarkdownTermsRoute: typeof sitemarkdownTermsRoute
}

const sitemarkdownRouteRouteChildren: sitemarkdownRouteRouteChildren = {
  sitemarkdownHelpRoute: sitemarkdownHelpRoute,
  sitemarkdownPrivacyRoute: sitemarkdownPrivacyRoute,
  sitemarkdownTermsRoute: sitemarkdownTermsRoute,
}

const sitemarkdownRouteRouteWithChildren =
  sitemarkdownRouteRoute._addFileChildren(sitemarkdownRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShareRoute: ShareRoute,
  sitemarkdownRouteRoute: sitemarkdownRouteRouteWithChildren,
  planPlanRoute: planPlanRoute,
  planProfileRoute: planProfileRoute,
  siteInquiryRoute: siteInquiryRoute,
  ShareImageDotpngRoute: ShareImageDotpngRoute,
  siteIndexRoute: siteIndexRoute,
  planPlanSettingsRoute: planPlanSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
